name: isearch_exp
dependencies:
- certifi=14.05.14=py27_0
- freetype=2.5.2=2
- ipython=3.2.0=py27_0
- ipython-notebook=3.2.0=py27_0
- jinja2=2.7.3=py27_1
- jsonschema=2.4.0=py27_0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_3
- mistune=0.6=py27_0
- nltk=3.0.3=np19py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.2=np19py27_0
- pip=7.1.0=py27_0
- ptyprocess=0.4=py27_0
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.3=py27_0
- python=2.7.10=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.4=py27_0
- pyyaml=3.11=py27_1
- pyzmq=14.7.0=py27_0
- qt=4.8.6=3
- readline=6.2=2
- setuptools=18.0.1=py27_0
- sip=4.16.5=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_0
- tk=8.5.18=0
- tornado=4.2=py27_0
- yaml=0.1.6=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - backports.ssl-match-hostname==3.4.0.2

